

[tool.ruff]
select = ["E", "F", "I", "UP"]
target-version = "py38"

[tool.ruff.isort]
known-first-party = ["merlin", "test"]

[tool.pytest.ini_options]
markers = [
    "slowtest: a test that takes longer than a couple seconds",
    "fullrun: a test that runs the full MERFISH decoding pipeline",
]
